#
# Module manifest for module 'PSServiceNow'
#
# Generated by: Sam Martin
#
# Generated on: 03/05/2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSServiceNow.psm1'

# Version number of this module.
ModuleVersion = '0.1.1'

# ID used to uniquely identify this module
GUID = 'b90d67da-f8d0-4406-ad74-89d169cd0633'

# Author of this module
Author = 'Sam Martin'

# Company or vendor of this module
CompanyName = 'None'

# Copyright statement for this module
Copyright = '(c) 2015 Sam. All rights reserved.'

# Description of the functionality provided by this module
# Description = 'This module provides cmdlets allowing you to retrieve information from your ServiceNow instance`s rest API'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
	'PSServiceNow-Tables.psm1',
	'PSServiceNow-Incidents.psm1',
	'PSServiceNow-Users.psm1',
	'PSServiceNow-ConfigurationManagement.psm1'
)

# Functions to export from this module
FunctionsToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = 'https://github.com/Toukakoukan/servicenow-powershell'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

